# version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: fitness_postgres
    environment:
      POSTGRES_DB: fitness_app
      POSTGRES_USER: alek
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alek"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fitness_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fitness_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: alek
      DB_PASSWORD: 123456
      DB_NAME: fitness_app
      FLASK_ENV: production
      FLASK_DEBUG: False
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fitness_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fitness_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fitness_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  fitness_network:
    driver: bridge